### ISSUE TITLE
Basic enchantment in chiseled bookshelf causes double rolls

### ISSUE THREAD

**Issue by ManaStar** [AstralOrdana/Enchantery#4]
I placed a sharpness 5 book into a chiseled bookshelf and chose an option that said sharpness, this caused the weapon to roll sharpness twice.

![image](https://github.com/AstralOrdana/Enchantery/assets/78570904/d2bd548c-37dd-4a51-998d-ced423616587)

**Comment by AstralOrdana** [comment]
damn, thought i fixed that

**Comment by AstralOrdana** [comment]
fixed for 0.0.9

**Comment by Explosif3005** [comment]
As far as i know it's still not fixed, i'm verifing if it's 0.0.9 but yeah

**Comment by Explosif3005** [comment]
Where is 0.0.9 version, i don't see it on curseforge and i have the bug

**Comment by NerjalNosk** [comment]
Stop searching on CF and just use Modrinth already
